# name=input("enter your name ", )
# print("your name is ", name)
# val1=input("entre a number to perform opratio n")
# val2=input("entr second number to get additio n result ")
# print("the sum of two number is ",val1+val2)
x=input()
print(x)